### ISSUE TITLE
Could I make the png center?

### ISSUE THREAD

**Issue by NE-SmallTown** [aantthony/console-png#5]
Thanks!

**Comment by aantthony** [comment]
This module doesn't support it, but you could try https://github.com/chjj/blessed

**Comment by NE-SmallTown** [comment]
Thanks, I will try

**Comment by NE-SmallTown** [comment]
Test and it seems can do that but there are flicker so the image just can be displayed a few seconds and I can't use console.log to print other things. Seems it have own screen system just like vim and can't be integrated with the terminal itself. Don't dig into it because it's not an active repo
