### ISSUE TITLE
image size adjustments

### ISSUE THREAD

**Issue by purohitdheeraj** [aantthony/console-png#7]
Hey Console-png is awesome! i liked that pixels of images are not distorted and overall image compression is good.

can we give image height and width ?

**Comment by aantthony** [comment]
Thanks 🙂

This module doesn’t support it directly. To resize something nicely requires a resampling algorithm (e.g. Lanczos) so I reckon you could use a module like https://www.npmjs.com/package/sharp to resize into a new buffer, and then pass the result into console-png

**Comment by purohitdheeraj** [comment]
Thanks alot👍
